import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>Next app pre-rendering Demo</h1>
          <p className={styles.text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus animi
            impedit suscipit architecto, odio inventore nostrum non neque dicta.
            Quam magni accusantium culpa distinctio tempore iure accusamus,
            dolorem nobis odit.
          </p>
          <p className={styles.text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus animi
            impedit suscipit architecto, odio inventore nostrum non neque dicta.
            Quam magni accusantium culpa distinctio tempore iure accusamus,
            dolorem nobis odit.
          </p>
          <Link href="/data/">
            <a className={styles.btn}>See data List</a>
          </Link>
        </div>
      </main>
    </div>
  );
}
